In [1]:
import pandas as pd
import yaml

### User defined
import variables_n_functions as vnf

config_file = open('config.yaml', 'r')
config = yaml.safe_load(config_file)

teams = config['teams']

### We initialize the df with the appropriate column names
df = pd.DataFrame(columns = vnf.columnas_df)

### The following variable is auxiliar to avoid duplicate requests
teams_aux = list(teams.keys())

### We recover the match history between every unique team - team combination, and store it in the df
for team_1 in teams.keys():
    teams_aux.remove(team_1)
    for team_2 in teams_aux:
        h2h = vnf.head2head(team_1, team_2, config['sports_token'])
        df = pd.concat([df] + [pd.DataFrame(pd.Series(h2h[k])).transpose() for k in range(len(h2h))])    
# RENAME COLUMN due to reserved keyword
df.rename(columns = {'time':'time_data'}, inplace = True)

In [8]:
import mysql.connector

client = mysql.connector.connect(**config['connection'])
cursor = client.cursor()

#### Create DB and Tables

with open('sql/create_h2h_db.sql') as ddl:
    cursor.execute(ddl.read())

with open('sql/create_h2h_source.sql') as ddl:
    cursor.execute(ddl.read())

In [9]:
def list_of_tuples(df):
    
    all_values = []
    
    for k in range(df.shape[0]):
        temp = df.iloc[k]
        temp = temp.astype(str)
        temp = tuple(temp)
        all_values.append(temp)
        
    return all_values

source_values = list_of_tuples(df)


for value in source_values:
    with open('sql/insert_h2h_source.sql') as dml:
        try:
            cursor.execute(dml.read(), value)
            dml.close()
        except mysql.connector.IntegrityError as err:
            print("Something went wrong: {}".format(err))
            dml.close()
            pass

client.commit()

In [11]:
pd.read_sql('SELECT * FROM h2h.sports_monks', con=client)

,id,league_id,season_id,stage_id,round_id,group_id,aggregate_id,venue_id,referee_id,localteam_id,...,formations,scores,time_data,coaches,standings,assistants,leg,colors,deleted,is_placeholder
0,18137071,501,18369,77453684,247462,None,None,8914,14859,62,...,"{'localteam_formation': '4-2-3-1', 'visitortea...","{'localteam_score': 1, 'visitorteam_score': 2,...","{'status': 'FT', 'starting_at': {'date_time': ...","{'localteam_coach_id': 23237, 'visitorteam_coa...","{'localteam_position': 2, 'visitorteam_positio...","{'first_assistant_id': 15817, 'second_assistan...",1/1,"{'localteam': {'color': '#2B72DE', 'kit_colors...",False,False
1,18137008,501,18369,77453684,247452,None,None,8909,14853,53,...,"{'localteam_formation': '4-3-3', 'visitorteam_...","{'localteam_score': 3, 'visitorteam_score': 0,...","{'status': 'FT', 'starting_at': {'date_time': ...","{'localteam_coach_id': 896805, 'visitorteam_co...","{'localteam_position': 2, 'visitorteam_positio...","{'first_assistant_id': 12118, 'second_assistan...",1/1,"{'localteam': {'color': '#339063', 'kit_colors...",False,False
2,18136904,501,18369,77453684,247434,None,None,8914,18748,62,...,"{'localteam_formation': '4-3-3', 'visitorteam_...","{'localteam_score': 1, 'visitorteam_score': 0,...","{'status': 'FT', 'starting_at': {'date_time': ...","{'localteam_coach_id': 50, 'visitorteam_coach_...","{'localteam_position': 6, 'visitorteam_positio...","{'first_assistant_id': 12118, 'second_assistan...",1/1,"{'localteam': {'color': '#2B72DE', 'kit_colors...",False,False
3,17947857,501,17141,77447500,240676,243965,None,8914,14468,62,...,"{'localteam_formation': '4-3-1-2', 'visitortea...","{'localteam_score': 4, 'visitorteam_score': 1,...","{'status': 'FT', 'starting_at': {'date_time': ...","{'localteam_coach_id': 50, 'visitorteam_coach_...","{'localteam_position': 1, 'visitorteam_positio...","{'first_assistant_id': 12770, 'second_assistan...",1/1,"{'localteam': {'color': '#2B72DE', 'kit_colors...",False,False
4,16475470,501,17141,77447501,194999,None,None,8909,14859,53,...,"{'localteam_formation': '4-2-3-1', 'visitortea...","{'localteam_score': 1, 'visitorteam_score': 1,...","{'status': 'FT', 'starting_at': {'date_time': ...","{'localteam_coach_id': 2163, 'visitorteam_coac...","{'localteam_position': 2, 'visitorteam_positio...","{'first_assistant_id': 14860, 'second_assistan...",1/1,"{'localteam': {'color': '#F0F0F0', 'kit_colors...",False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,11783968,501,1928,3209,51857,None,None,8946,None,66,...,"{'localteam_formation': None, 'visitorteam_for...","{'localteam_score': 2, 'visitorteam_score': 1,...","{'status': 'FT', 'starting_at': {'date_time': ...","{'localteam_coach_id': None, 'visitorteam_coac...","{'localteam_position': None, 'visitorteam_posi...","{'first_assistant_id': None, 'second_assistant...",1/1,None,False,False
138,373750,501,1927,3206,51826,225153,None,8946,None,66,...,"{'localteam_formation': None, 'visitorteam_for...","{'localteam_score': 1, 'visitorteam_score': 2,...","{'status': 'FT', 'starting_at': {'date_time': ...","{'localteam_coach_id': None, 'visitorteam_coac...","{'localteam_position': None, 'visitorteam_posi...","{'first_assistant_id': None, 'second_assistant...",1/1,None,False,False
139,373785,501,1927,3207,51843,None,None,8914,None,62,...,"{'localteam_formation': None, 'visitorteam_for...","{'localteam_score': 2, 'visitorteam_score': 0,...","{'status': 'FT', 'starting_at': {'date_time': ...","{'localteam_coach_id': None, 'visitorteam_coac...","{'localteam_position': None, 'visitorteam_posi...","{'first_assistant_id': None, 'second_assistant...",1/1,None,False,False
140,373859,501,1927,3207,51837,None,None,8946,None,66,...,"{'localteam_formation': None, 'visitorteam_for...","{'localteam_score': 2, 'visitorteam_score': 1,...","{'status': 'FT', 'starting_at': {'date_time': ...","{'localteam_coach_id': None, 'visitorteam_coac...","{'localteam_position': None, 'visitorteam_posi...","{'first_assistant_id': None, 'second_assistant...",1/1,None,False,False
141,11783885,501,1927,3207,51830,None,None,8914,None,62,...,"{'localteam_formation': None, 'visitorteam_for...","{'localteam_score': 0, 'visitorteam_score': 3,...","{'status': 'FT', 'starting_at': {'date_time': ...","{'localteam_coach_id': None, 'visitorteam_coac...","{'localteam_position': None, 'visitorteam_posi...","{'first_assistant_id': None, 'second_assistant...",1/1,None,False,False

In [25]:
1

1